name: 'dbt_with_udf_example'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_with_udf_example'

# These configurations specify where dbt should look for different types of files.
# For Databricks asset bundles, we put everything in src, as you may have
# non-dbt resources in your project.
model-paths: ["src/models"]
analysis-paths: ["src/analyses"]
test-paths: ["src/tests"]
seed-paths: ["src/seeds"]
macro-paths: ["src/macros"]
snapshot-paths: ["src/snapshots"]

clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  pyudfs:
   percentage_increase:
    args:
      - name: a
        type: DOUBLE
      - name: b
        type: DOUBLE
    returns: DOUBLE
    whl_path: "pyudf/udf_py-0.1.0-py3-none-any.whl"
    package_name: udf
    module_name: helpers

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views by default. These settings can be overridden in the
# individual model files using the `{{ config(...) }}` macro.
models:
  dbt_with_udf_example:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
